### ISSUE TITLE
[EVENT-002] 이벤트 게시글 상세조회

### ISSUE THREAD

**Issue by Yong-ga-ri** [variety-crew/bangflix-frontend#19]
# 제목
이벤트 게시글 상세 조회

## 설명
- 제목, 작성일시, 작성자, 내용 조회

## TODO
- [ ] 특정 이벤트 상세 조회 폼

## 세부 개발 요구 사항
- [ ] 상세 조회 폼
- [ ] 이벤트 카드
- [ ] 이벤트 세부 정보
- [ ] 이벤트 관련 이미지
- [ ] 권한 별 수정/삭제 Routing
