### ISSUE TITLE
[EVENT-003] 이벤트 게시글 작성

### ISSUE THREAD

**Issue by Yong-ga-ri** [variety-crew/bangflix-frontend#20]
# 제목
- 이벤트 게시글 등록

## 설명
- 이벤트 게시글을 등록한다.

## TODO
- [ ] 제목, 내용 입력
- [ ] 작성일시는 현재시간 자동 입력

## 세부 개발 요구 사항
- [ ] 이벤트 카테고리 설정
- [ ] 존재 테마 내 특정 테마 선택
- [ ] 이미지 업로드
- [ ] 이벤트 등록/수정 구별
