### ISSUE TITLE
[EVENT-004] 이벤트 게시글 수정

### ISSUE THREAD

**Issue by Yong-ga-ri** [variety-crew/bangflix-frontend#21]
# 제목
- 이벤트 게시글 수정

## 설명
- 이벤트 게시글을 수정한다.

## TODO
- [ ] 제목, 내용 수정
- [ ] 수정 시 작성일시가 수정일시로 업데이트

## 세부 개발 요구 사항
- [ ] 기존 데이터 불러오기
- [ ] 이벤트 등록/수정 구별
