### ISSUE TITLE
[BOARD-002] 커뮤니티 게시글 상세조회

### ISSUE THREAD

**Issue by Yong-ga-ri** [variety-crew/bangflix-frontend#3]
# 제목
- 커뮤니티 게시글 상세조회

## 설명
- 커뮤니티 게시글 상세조회

## TODO
- [ ] 미리보기 컴포넌트 리스트 적용
- [ ] 보드 상세보기 적용
- [ ] 권한별 추가 메뉴 적용
- [ ] 미리보기 컴포넌트 리스트 부분 무한 스크롤 적용
- [ ] 댓글 작성 폼 및 댓글 컴포넌트 추가

## 세부 개발 요구 사항
- 권한별 추가 메뉴 적용
    - [ ] 구독(user), 수정(작성자/관리자), 삭제(작성자/관리자)
