### ISSUE TITLE
[SUBSCRIBE] 게시글 구독 및 알림

### ISSUE THREAD

**Issue by Yong-ga-ri** [variety-crew/bangflix-frontend#30]
# 제목
- 구독

## 설명
- 특정 사용자가 특정 게시글을 구독한다.
- 이후, 특정 게시글에 댓글이 달리면, 해당 게시글을 구독한 사용자에게 알림이 발송된다.

## TODO
- [ ] 특정 사용자가 특정 게시글을 구독한다.
- [ ] 제3자(서비스 내 사용자)가 특정 게시글에 댓글을 생성한다.
- [ ] 해당 게시글을 구독한 사용자 및 사용자들에게 알림이 발송된다.

## 세부 개발 요구 사항
- [ ] 특정 사용자가 특정 게시글 구독
- [ ] 제 3자가 해당 게시글에 댓글 작성
- [ ] 해당 게시글을 구독한 사용자 및 사용자들에게 알림 발송

## 관련 이슈 사항 (선택사항)
- #3 
- #6
