### ISSUE TITLE
[BOARD-003] [BOARD-004] 커뮤니티 게시글 작성/수정

### ISSUE THREAD

**Issue by Yong-ga-ri** [variety-crew/bangflix-frontend#4]
# 제목
- 커뮤니티 게시글 작성/수정

## 설명
- 커뮤니티 게시글 작성
- 커뮤니티 게시글 수정

## TODO
- [ ] 입력 폼 컴포넌트 적용

## 세부 개발 요구 사항
- [ ] 이미지 업로드 기능
- [ ] 등록/수정에 따른 상태 분리
