### ISSUE TITLE
[BOARD-006] [BOARD-007] 커뮤니티 게시글 구독/구독취소

### ISSUE THREAD

**Issue by Yong-ga-ri** [variety-crew/bangflix-frontend#6]
# 제목
- 커뮤니티 게시글 구독/구독취소

## 설명
- 커뮤니티 게시글 구독
- 커뮤니티 게시글 구독 취소

## TODO
- [ ] 커뮤니티 게시글 구독
- [ ] 커뮤니티 게시글 구독취소
- [ ] 커뮤니티 게시글 상세페이지에서 가능

## 세부 개발 요구 사항
- [ ] 서버에서 구독에 대한 관리 필요
